# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np
from numpy.random import randint as ri

## indexing and slicing

#### vector indexing : ANSWER

In [6]:
arr = np.arange(0,11)
print("Array:",arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
print("Array:",arr)
print("Element at 7th index is:", arr[7])


print("Elements from 3rd to 5th index are:", arr[3:5])


print("Elements up to 4th index are:", arr[:5])


print("Reverse the elements:", arr[::-1])



arr = np.arange(0,21,2)
print("New array:",arr)


print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4]
Elements up to 4th index are: [0 1 2 3 4]
Reverse the elements: [10  9  8  7  6  5  4  3  2  1  0]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [3]:



print("Element at 7th index is:", arr[*])


print("Elements from 3rd to 5th index are:", arr[*])


print("Elements up to 4th index are:", arr[*])


print("Reverse the elements:", arr[*])



arr = np.arange(0,21,2)
print("New array:",arr)


print("Elements at 2nd, 4th, and 9th index are:", arr[*]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4]
Elements up to 4th index are: [0 1 2 3 4]
Reverse the elements: [10  9  8  7  6  5  4  3  2  1  0]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


#### matrix indexing 

In [9]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])


print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")


print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:,3:])


print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[:2,[1,3]])

Matrix of random 2-digit numbers
--------------------------------
 [[75 30 87 10 14]
 [33 68 41 97 61]
 [30 63 81 10 62]]

Double bracket indexing
------------------------
Element in row index 1 and column index 2: 41

Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 41

Row or column extract
----------------------
Entire row at index 2: [30 63 81 10 62]
Entire column at index 3: [10 97 10]

Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[97 61]
 [10 62]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[30 10]
 [68 97]]


In [11]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[*][*])


print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[*,*])
print("\nRow or column extract\n----------------------")


print("Entire row at index 2:", mat[*])
print("Entire column at index 3:", mat[:,*])


print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[*,*])


print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[*,[*,*]])

Matrix of random 2-digit numbers
--------------------------------
 [[33 98 11 67 14]
 [86 48 46 74 95]
 [79 13 47 99 59]]

Double bracket indexing
------------------------
Element in row index 1 and column index 2: 46

Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 46

Row or column extract
----------------------
Entire row at index 2: [79 13 47 99 59]
Entire column at index 3: [67 74 99]

Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[74 95]
 [99 59]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[98 67]
 [48 74]]


## Fancy indexing and index trick
NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

#### Indexing with Arrays of Indices

In [10]:
a = np.arange(12)**2                      # the first 12 square numbers
i = np.array([ 1,1,3,8,5] )              # an array of indices
print(a)
print(a[i])   

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25]


In [6]:
a = np.arange(12)**2                      # the first 12 square numbers
i = np.array([ 1,1,3,8,5] )              # an array of indices
print(a)
print(*)                              # the elements of a at the positions i

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25]


In [11]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
print(j**2)      

[[ 9 16]
 [81 49]]


In [5]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
print(*)                                      # the elements of a at the positions j

array([[ 9, 16],
       [81, 49]])

We can also give indexes for more than one dimension. The arrays of indices for each dimension must have the same shape.

In [17]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
i = np.array( [ [0,1],                        # indices for the first dim of a
                [1,2] ] )
j = np.array( [ [2,1],                        # indices for the second dim
                [3,3] ] )

a[i,j]  

array([[ 2,  5],
       [ 7, 11]])

In [5]:
i = np.array( [ [0,1],                        # indices for the first dim of a
                [1,2] ] )
j = np.array( [ [2,1],                        # indices for the second dim
                [3,3] ] )

a[*]                                        # Fill * to produce output given below

array([[ 2,  5],
       [ 7, 11]])

In [6]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

Naturally, we can put i and j in a sequence (say a list) and then do the indexing with the list.

In [9]:
l = [i,j]
a[l]          # equivalent to a[i,j]

array([[ 2,  5],
       [ 7, 11]])

However, we can not do this by putting i and j into an array, because this array will be interpreted as indexing the first dimension of a.

In [21]:
s = np.array( [i,j] )
s
a[s]                                       # not what we want

IndexError: index 3 is out of bounds for axis 0 with size 3

In [22]:
a[tuple(s)]                                # repalce *  with tuple

array([[ 2,  5],
       [ 7, 11]])

In [23]:
time = np.linspace(20,145,5)                 # linspace num=5, from 20 to 145
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [14]:
time = np.linspace(*,*,*)                 # linspace num=5, from 20 to 145
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [24]:
data = np.sin(np.arange(20)).reshape(5,4)      # 4 time-dependent series
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [25]:
# index of the maxima for each series using argmax
ind = data.argmax(axis=0) 
ind

array([2, 0, 3, 1], dtype=int64)

In [17]:
# index of the maxima for each series using argmax
ind = data.*(axis=*) 
ind

array([2, 0, 3, 1], dtype=int64)

In [26]:
time_max = time[ind]                       # times corresponding to the maxima
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [21]:
time_max = time[*]                       # times corresponding to the maxima
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

You can also use indexing with arrays as a target to assign to:

In [27]:
#Assign 0 at index position 1,3,4

a = np.arange(5)
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [30]:
#Assign 0 at index position 1,3,4

a = np.arange(5)
a[[*,*,*]] = 0
a

array([0, 0, 2, 0, 0])

In [28]:
#Indexing with boolean arrays
#Generate 0 to 12 elements array with diemension 3*4
a = np.arange(12).reshape(3,4)

b = a > 4       #Check if a has any element greater than 4
b    

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
#Indexing with boolean arrays
#Generate 0 to 12 elements array with diemension 3*4
a = np.arange(*).reshape(*,*)

b = a > *       #Check if a has any element greater than 4
b               # b is a boolean with a's shape

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
a[b]                                       # 1d array with the selected elements

array([ 5,  6,  7,  8,  9, 10, 11])

This property can be very useful in assignments:

In [34]:
a[b] = 0                                   # All elements of 'a' higher than 4 become 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

## slicing and Subetting 

In [30]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)

print ("\nSliced matrix with :2 and :2 ")
mat_slice = mat[:2,:2]

print(mat_slice)
print ("\nChange the sliced matrix value of first element")

mat_slice[0,0] = 1000
print (mat_slice)

print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)


# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)


print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)


print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Sliced matrix with :2 and :2 
[[11 12]
 [21 22]]

Change the sliced matrix value of first element
[[1000   12]
 [  21   22]]

But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]

Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix
[[1000   12]
 [  21   22]]

But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [12]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)

print ("\nSliced matrix with :2 and :2 ")
mat_slice = mat[*,*]

print(mat_slice)
print ("\nChange the sliced matrix value of first element")

mat_slice[*,*] = 1000
print (mat_slice)

print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)


# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)


print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)


print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix
[[1000   12]
 [  21   22]]

But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]

Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix
[[1000   12]
 [  21   22]]

But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


## Updating  arrays
* insert 
* append
* delete

In [31]:
import numpy as np
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [32]:
# Insert 5  in array x before index 1 
np.insert(x,1,5 )

array([ 0.,  5.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
       12., 13., 14., 15.])

In [33]:
# Insert row with 5 before 1 row
np.insert(x,1,5, axis=0)

array([[ 0.,  1.,  2.,  3.],
       [ 5.,  5.,  5.,  5.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [35]:
# Insert 5 before 1 column
np.insert(x,1,5, axis=1)

array([[ 0.,  5.,  1.,  2.,  3.],
       [ 4.,  5.,  5.,  6.,  7.],
       [ 8.,  5.,  9., 10., 11.],
       [12.,  5., 13., 14., 15.]])

In [56]:
# Insert 5 before 1 column
x = np.arange(16).reshape(2,2,4)
np.insert(x,1,5, axis=1)

array([[[ 0,  1,  2,  3],
        [ 5,  5,  5,  5],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [ 5,  5,  5,  5],
        [12, 13, 14, 15]]])

In [24]:
# Insert 5 before 1 column
np.insert(x,*,*, axis=*)

array([[[ 0.,  1.,  2.,  3.],
        [ 5.,  5.,  5.,  5.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [ 5.,  5.,  5.,  5.],
        [12., 13., 14., 15.]]])

In [52]:
#Append two arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9]])

In [57]:
np.append(arr1, arr2, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.append(*, *, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#Verify if axis is not mentioned
np.append(arr1, arr2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
#Delete 1 row in x
x = np.arange(16.0).reshape(4, 4)
np.delete(x,1,axis=0)

array([[ 0.,  1.,  2.,  3.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [35]:
#Delete 1 row in x
np.delete(*,*,*)

array([[ 0.,  1.,  2.,  3.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

## diagonal operations 

In [61]:
x = np.arange(9).reshape((3,3));x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
#Get Diagonal Elements of x. Use np.diag
np.diag(x)

array([0, 4, 8])

In [63]:
#Get upper diagonal elemets, to produce given output
np.diag(x, k=1)

array([1, 5])

In [10]:
#Get upper diagonal elemets, to produce given output
np.diag(x, k=*)

array([1, 5])

In [64]:
#Get upper diagonal elemets. to produce given output
np.diag(x, k=-1)

array([3, 7])

In [65]:
#Create a two-dimensional array with the flattened input as a diagonal. use np.diagflat

np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [13]:
#Create a two-dimensional array with the flattened input as a diagonal. use np.diagflat

*([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])