# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [10]:
mat1 = np.random.randint(1,9,9).reshape(3,3)
mat2 = np.random.randint(1,9,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1 + mat2)
print("\nMultiplication\n------------------\n", np.multiply(mat1,mat2))


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1 - 2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", mat1 + 100)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1 ** 3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[4 8 6]
 [6 5 7]
 [5 5 6]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[8 8 5]
 [7 5 1]
 [7 5 1]]

Addition
------------------
 [[12 16 11]
 [13 10  8]
 [12 10  7]]

Multiplication
------------------
 [[32 64 30]
 [42 25  7]
 [35 25  6]]

Division
------------------
 [[0.5        1.         1.2       ]
 [0.85714286 1.         7.        ]
 [0.71428571 1.         6.        ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[-4  8  8]
 [ 4  5 19]
 [ 1  5 16]]

Addition of a scalar (100)
-------------------------
 [[104 108 106]
 [106 105 107]
 [105 105 106]]

Exponentiation, matrix cubed here
----------------------------------------
 [[ 64 512 216]
 [216 125 343]
 [125 125 216]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[2.         2.82842712 2.44948974]
 [2.44948974 2.23606798 2.64575131]
 [2.23

In [ ]:
mat1 = ****
mat2 = ****
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", ****)
print("\nMultiplication\n------------------\n", ****)


print("\nDivision\n------------------\n", *****)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", ******)


print("\nAddition of a scalar (100)\n-------------------------\n", ******)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", *******)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",***********)

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [46]:
from numpy.random import randint as ri
mat1 = np.random.randint(1,9,9).reshape(3,3)
mat2 = np.random.randint(1,9,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1, axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat1, axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))

mat1 = np.random.randint(1,99,9).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))




1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[4 7 5]
 [5 4 8]
 [8 8 3]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[2 3 5]
 [8 2 5]
 [6 1 8]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 52

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [17 19 16]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [16 17 19]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [140 160 192]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [160 224 120]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.777777777777778

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 1

In [ ]:
from numpy.random import randint as ri
mat1 = *******
mat2 = *******
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",********)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",********)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",*******)


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",*********)
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",********)


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",********)
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",********)


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",******)


mat1 = ************
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",****)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",**********)


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",*********)


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",**********)


###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [13]:
##Solution
x = np.arange(9).reshape(3,3)
x.reshape(9,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### 4.Sort

In [16]:
A = np.random.randint(1,100,9) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))        


Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [ 9 23 99 80 47 96 89 91 57]

Here is the sorted vector
 -------------------------------------------------- 
 [ 9 23 47 57 80 89 91 96 99]


In [19]:
M = np.random.randint(1,9,25).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, axis=1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[7 1 8 3 3]
 [5 3 7 2 2]
 [7 8 1 2 4]
 [1 7 1 4 7]
 [7 6 1 1 2]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[1 3 3 7 8]
 [2 2 3 5 7]
 [1 2 4 7 8]
 [1 1 4 7 7]
 [1 1 2 6 7]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[1 1 1 1 2]
 [5 3 1 2 2]
 [7 6 1 2 3]
 [7 7 7 3 4]
 [7 8 8 4 7]]


In [ ]:
M = ****** #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",****)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",******) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",*********)

### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [21]:
# Fill the following ***** with appropriate solution.
a= np.random.randint(1,9,9)
b= np.random.randint(1,9,9)
c= np.random.randint(1,9,9)

print("a:", a)
print("b:", b)
print("c:", c)

print("Min of a:", np.min(a))
print("Min of b:", np.min(a))


print("Min of a location:", np.argmin(a))
print("Min of b location:", np.argmin(b))
print("Min of c location:", np.argmin(c))

print("Max of a:", np.max(a))
print("Max of b:",np.max(a))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))


a: [1 8 7 7 7 1 6 7 4]
b: [3 1 6 8 7 3 1 5 3]
c: [3 8 2 4 5 8 5 2 2]
Min of a: 1
Min of b: 1
Min of a location: 0
Min of b location: 1
Min of c location: 2
Max of a: 8
Max of b: 8
Max of a location: 1
Max of b location: 3
Max of c location: 1


In [12]:
# Fill the following ***** with appropriate solution.
a=
b=
c=

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", ****)
print("Max of b:",****)


print("Max of a location:", *****)
print("Max of b location:", *****)
print("Max of c location:", *****)

print("Max of a:", *****)
print("Max of b:", ****)


print("Max of a location:", ******)
print("Max of b location:", ******)
print("Max of c location:", ******)



Max of a: 50
Max of b: 3
Max of a location: 3
Max of b location: 3
Max of c location: 3
Max of a: 20
Max of b: 0
Max of a location: 0
Max of b location: 0
Max of c location: 0


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [23]:

mat1 = np.random.randint(1,9,9).reshape(3,3)
mat2 = np.random.randint(1,9,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1, mat2))


1st Matrix of random single-digit numbers
----------------------------------------
 [[4 2 3]
 [1 5 1]
 [7 5 5]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 1 2]
 [6 1 5]
 [6 1 3]]

Sq-root of 1st matrix using np
------------------
 [[2.         1.41421356 1.73205081]
 [1.         2.23606798 1.        ]
 [2.64575131 2.23606798 2.23606798]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[  54.59815003    7.3890561    20.08553692]
 [   2.71828183  148.4131591     2.71828183]
 [1096.63315843  148.4131591   148.4131591 ]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.60205999 0.30103    0.47712125]
 [0.         0.69897    0.        ]
 [0.84509804 0.69897    0.69897   ]]

Modulo reminder using np
 -------------------------------------------------- 
 [[1 0 1]
 [1 0 1]
 [1 0 2]]


In [ ]:

mat1 = *****
mat2 = *****
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",*****)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",*****)


print("\nSq-root of 1st matrix using np\n------------------\n", *****)


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", *****)


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", *****)


print("\nModulo reminder using np\n",'-'*50,"\n", *****)


### 7.Generating matrices from distributions

In [25]:

print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(2,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,9).reshape(3,3)) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,6,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.00670708 0.94841089 0.05647196]
 [0.10130117 0.96627106 0.12551209]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 1.07262795 -0.48455986 -0.75089121]
 [-0.98039052 -0.94592639  0.3989835 ]]
Random integer vector: [16 53 22 38 14 98 77 17  6  5]

Random integer matrix
[[14 67  5]
 [39 25 39]
 [49 88 24]]

20 samples drawn from a dice throw: [1 5 5 5 2 3 5 1 3 2 3 4 2 1 5 2 2 3 3 3]


In [2]:

print("Random number generation (from Uniform distribution)")
print(******) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(******)

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(********) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",*******) # 20 samples drawn from a dice throw

SyntaxError: invalid syntax (<ipython-input-2-92f026fcc020>, line 3)

### 8.Find the nearest value from a given number in an array using NumPy.

In [30]:
#Steps
#Create an array of 5 random element from 1 to 12
mat1 = np.random.randint(1,12,5)
print ("Created Matrix is : ",mat1)
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element
np.argmin(10 - mat1)

Created Matrix is :  [6 8 1 9 7]


3

In [21]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

4.859577122593637


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [45]:
mat1 = np.array([0,1,2])
maat2 = np.array([mat1 * i for i in range(3)])
maat2

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])